// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1AgHNjV2LJkXBpnPVw8c5Peh8H7FyLQ',
    appId: '1:582938785371:web:7a7aeba9bb987b4bbfb17e',
    messagingSenderId: '582938785371',
    projectId: 'fir-74397',
    authDomain: 'fir-74397.firebaseapp.com',
    storageBucket: 'fir-74397.appspot.com',
    measurementId: 'G-MPNGMVL6EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGas31PdA1pYIlAfUi4RkA8OUXU0kpQXw',
    appId: '1:582938785371:android:820f4ddc65d7e20bbfb17e',
    messagingSenderId: '582938785371',
    projectId: 'fir-74397',
    storageBucket: 'fir-74397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGETA-GpC2WitcBsRKfCxr0epAY54sqA',
    appId: '1:582938785371:ios:c51f0e373da28fc5bfb17e',
    messagingSenderId: '582938785371',
    projectId: 'fir-74397',
    storageBucket: 'fir-74397.appspot.com',
    iosBundleId: 'com.example.supermarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGETA-GpC2WitcBsRKfCxr0epAY54sqA',
    appId: '1:582938785371:ios:c51f0e373da28fc5bfb17e',
    messagingSenderId: '582938785371',
    projectId: 'fir-74397',
    storageBucket: 'fir-74397.appspot.com',
    iosBundleId: 'com.example.supermarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV1AgHNjV2LJkXBpnPVw8c5Peh8H7FyLQ',
    appId: '1:582938785371:web:70befdc6f3df132ebfb17e',
    messagingSenderId: '582938785371',
    projectId: 'fir-74397',
    authDomain: 'fir-74397.firebaseapp.com',
    storageBucket: 'fir-74397.appspot.com',
    measurementId: 'G-LCVGR2ZH6Y',
  );
}
